"""empty message

Revision ID: 0597f17cc64d
Revises: 88c25e6a54f1
Create Date: 2025-04-12 23:55:25.404449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0597f17cc64d'
down_revision: Union[str, None] = '88c25e6a54f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kakao_id', sa.String(length=64), nullable=False),
    sa.Column('plusfriend_user_key', sa.String(length=64), nullable=True),
    sa.Column('app_user_id', sa.String(length=64), nullable=True),
    sa.Column('kakao_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_user_id'),
    sa.UniqueConstraint('kakao_id'),
    sa.UniqueConstraint('plusfriend_user_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
