"""create user table

Revision ID: 6407cf972fec
Revises: 
Create Date: 2026-03-13 01:37:18.219757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6407cf972fec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keycloak_id', sa.String(length=64), nullable=False),
    sa.Column('kakao_id', sa.String(length=64), nullable=False),
    sa.Column('plusfriend_user_key', sa.String(length=64), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('app_user_id', sa.String(length=64), nullable=True),
    sa.Column('kakao_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_user_id'),
    sa.UniqueConstraint('app_user_id', name='uq_app_user_id'),
    sa.UniqueConstraint('kakao_id', name='uq_kakao_id'),
    sa.UniqueConstraint('keycloak_id', name='uq_keycloak_id'),
    sa.UniqueConstraint('plusfriend_user_key')
    )
    op.create_index(op.f('ix_user_kakao_id'), 'user', ['kakao_id'], unique=True)
    op.create_index(op.f('ix_user_keycloak_id'), 'user', ['keycloak_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_keycloak_id'), table_name='user')
    op.drop_index(op.f('ix_user_kakao_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
